FROM golang:alpine as builder

WORKDIR /app

COPY . .

RUN CGO_ENABLED=0 go build components/follower/main.go

FROM alpine:latest

RUN apk add --no-cache tzdata

COPY --from=builder app/main /app

CMD ["/app"]